export { default as article } from '@/api/modules/article'
export { default as category } from '@/api/modules/category'
export { default as tag } from '@/api/modules/tag'
export { default as user } from '@/api/modules/user'
export { default as comment } from '@/api/modules/comment'
export { default as auth } from '@/api/modules/auth'
export { default as setting } from '@/api/modules/setting'
export { default as notification } from '@/api/modules/notification'