// 列表获取
export const FETCH_LIST_REQUEST = 'FETCH_LIST_REQUEST'
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS'
export const FETCH_LIST_FAILURE = 'FETCH_LIST_FAILURE'

// 详情获取
export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST'
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS'
export const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE'

// 编辑
export const EDIT_ITEM_REQUEST = 'EDIT_ITEM_REQUEST'
export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS'
export const EDIT_ITEM_FAILURE = 'EDIT_ITEM_FAILURE'

// 删除
export const DELETE_ITEM_REQUEST = 'FETCH_LIST_REQUEST'
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS'
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE'

// 创建
export const CREATE_ITEM_REQUEST = 'CREATE_ITEM_REQUEST'
export const CREATE_ITEM_FAILURE = 'CREATE_ITEM_FAILURE'
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS'